// Diploma options used in CreateSessionModal
export const DIPLOMAS = [
  "BAC",
  "DEUG",
  "DUT",
  "BAC+2",
  "Bachelor",
  "Licence",
  "Master",
  "Engineer",
  "PhD",
];

// Multi‑language translations
export const translations = {
  en: {
    brand: "VocaHire",
    welcome: "Good morning,",
    name: "Alex",
    createSession: "Create Session",
    history: "Recent Sessions",
    importTitle: "New Session",
    jobTitle: "Job Title",
    qualities: "Qualities",
    candidateCount: "Expected Candidates",
    diploma: "Diploma",
    experience: "Experience (Years)",
    criterias: "Evaluation Criterias",
    date: "Interview Date",
    cancel: "Cancel",
    confirm: "Launch session",
    processing: "Analyzing candidate",
    resultTitle: "Analysis complete",
    close: "Close report",
    addCandidate: "Add candidate",
    candidatePlaceholder: "Enter candidate name...",
    uploadAudio: "Upload audio",
    analyze: "Analyze",
    reanalyze: "Re-analyze",
    back: "Back to dashboard",
    fileSelected: "File ready",
    score: "Score",
    details: "View Details",
    deleteCandidate: "Delete candidate",
    steps: [
      { id: 0, label: "Uploading media..." },
      { id: 1, label: "Extracting audio..." },
      { id: 2, label: "AI Analysis..." },
      { id: 3, label: "Scoring..." },
      { id: 4, label: "Finalizing..." },
    ],
  },
  fr: {
    brand: "VocaHire",
    welcome: "Bonjour,",
    name: "Alex",
    createSession: "Créer une session",
    history: "Sessions récentes",
    importTitle: "Nouvelle session",
    jobTitle: "Intitulé du poste",
    qualities: "Qualités",
    candidateCount: "Candidats attendus",
    diploma: "Diplôme",
    experience: "Expérience (Années)",
    criterias: "Critères d'évaluation",
    date: "Date de l'entretien",
    cancel: "Annuler",
    confirm: "Lancer la session",
    processing: "Analyse du candidat",
    resultTitle: "Analyse terminée",
    close: "Fermer le rapport",
    addCandidate: "Ajouter un candidat",
    candidatePlaceholder: "Nom du candidat...",
    uploadAudio: "Charger l'audio",
    analyze: "Analyser",
    reanalyze: "Réanalyser",
    back: "Retour au tableau de bord",
    fileSelected: "Fichier prêt",
    score: "Note",
    details: "Voir détails",
    deleteCandidate: "Supprimer le candidat",
    steps: [
      { id: 0, label: "Chargement du média..." },
      { id: 1, label: "Extraction audio..." },
      { id: 2, label: "Analyse IA..." },
      { id: 3, label: "Notation..." },
      { id: 4, label: "Finalisation..." },
    ],
  },
  ar: {
    brand: "VocaHire",
    welcome: "صباح الخير،",
    name: "أليكس",
    createSession: "إنشاء جلسة",
    history: "الجلسات الأخيرة",
    importTitle: "جلسة جديدة",
    jobTitle: "المسمى الوظيفي",
    qualities: "الصفات",
    candidateCount: "العدد المتوقع",
    diploma: "الدرجة العلمية",
    experience: "سنوات الخبرة",
    criterias: "معايير التقييم",
    date: "تاريخ المقابلة",
    cancel: "إلغاء",
    confirm: "إطلاق الجلسة",
    processing: "تحليل المرشح",
    resultTitle: "تم التحليل",
    close: "إغلاق التقرير",
    addCandidate: "إضافة مرشح",
    candidatePlaceholder: "اسم المرشح...",
    uploadAudio: "رفع الصوت",
    analyze: "تحليل",
    reanalyze: "إعادة التحليل",
    back: "العودة للوحة التحكم",
    fileSelected: "الملف جاهز",
    score: "النتيجة",
    details: "عرض التفاصيل",
    deleteCandidate: "حذف المرشح",
    steps: [
      { id: 0, label: "جاري الرفع..." },
      { id: 1, label: "استخراج الصوت..." },
      { id: 2, label: "تحليل الذكاء الاصطناعي..." },
      { id: 3, label: "توليد الدرجات..." },
      { id: 4, label: "إتمام التقرير..." },
    ],
  },
};

// Initial demo data (optional – can also be kept inside App)
export const initialSessions = [
  {
    id: "1",
    jobTitle: "Senior Frontend Engineer",
    date: "2023-10-24",
    candidates: [
      {
        id: "c1",
        name: "Sarah Chen",
        analyzed: true,
        audioFile: "interview_v01.mp3",
        totalScore: 8.7,
        results: {
          content_relevance: 0.9,
          vocal_confidence: 0.85,
          clarity_of_speech: 0.92,
          fluency: 0.81,
          short_feedback: "Exceptional clarity and technical depth.",
        },
      },
    ],
  },
];